-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

local mocha = require("mocha")
---@module 'hl'

-- --- Estética e Decoração ---

hl.config({
    general = {
        gaps_in = 4,
        gaps_out = 8,
        border_size = 2,
        layout = "dwindle",
        allow_tearing = false,
        col = {
            active_border = { colors = { mocha.mauve, mocha.lavender }, angle = 45 },
            inactive_border = mocha.surface0,
        },
    },
})

hl.config({
    decoration = {
        rounding = 12,
        active_opacity = 0.98,
        inactive_opacity = 0.88,
        blur = {
            enabled = true,
            size = 6,
            passes = 3,
            new_optimizations = true,
            ignore_opacity = true,
            special = true,
        },
        shadow = {
            enabled = true,
            range = 15,
            render_power = 3,
            color = "rgba(11111b66)",
        },
    },
})

hl.config({
    animations = {
        enabled = true,
    },
})
hl.curve("balanco", {
    type = "bezier",
    points = { { 0.05, 0.9 }, { 0.1, 1.05 } },
})
hl.animation({ leaf = "windows", enabled = true, speed = 6, bezier = "balanco", style = "slide" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 6, bezier = "balanco", style = "slide" })
hl.animation({ leaf = "fade", enabled = true, speed = 6, bezier = "balanco" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 8, bezier = "balanco", style = "slidefade 20%" })

hl.config({
    dwindle = {
        preserve_split = true,
    },
})

hl.config({
    misc = {
        disable_hyprland_guiutils_check = true,
        force_default_wallpaper = 0,
        disable_hyprland_logo = true,
        enable_swallow = true,
        swallow_regex = "^(kitty|alacritty)$",
        focus_on_activate = false,
    },
})
hl.config({
    debug = {
        vfr = true,
    },
})
