-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- --- Monitores ---

hl.monitor({
    output   = "eDP-1",
    mode     = "1920x1080@144",
    position = "0x0",
    scale    = 1,
})

hl.monitor({
    output   = "HDMI-A-1",
    mode     = "1920x1080@60",
    position = "auto",
    scale    = 1,
})

-- --- Entrada ---

hl.config({
    input = {
        kb_layout = "br", "us",
        kb_variant = "abnt2", "intl",
        kb_model = "abnt2",
        repeat_delay = 300,
        repeat_rate = 50,
        follow_mouse = 1,
        touchpad = {
            natural_scroll = true,
            disable_while_typing = true,
            tap_to_click = true,
            scroll_factor = 0.5,
        },
        sensitivity = 0,
        accel_profile = "flat",
    },
})

hl.config({
    cursor = {
        no_hardware_cursors = true,
        no_warps = true,
        inactive_timeout = 5,
    },
})
