-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- --- Regras de Janela ---

hl.window_rule({
    name  = "float_2",
    match = {
        class = "^(pavucontrol)$",
    },
    float = true,
})

hl.window_rule({
    name  = "float_3",
    match = {
        class = "^(blueman-manager)$",
    },
    float = true,
})

hl.window_rule({
    name  = "float_4",
    match = {
        class = "^(nm-connection-editor)$",
    },
    float = true,
})

hl.window_rule({
    name  = "float_5",
    match = {
        class = "^(copyq)$",
    },
    float = true,
})

hl.window_rule({
    name  = "float_6",
    match = {
        class = "^(galculator)$",
    },
    float = true,
})

hl.window_rule({
    name  = "size_50__50__7",
    match = {
        class = "^(copyq)$",
    },
    size = { "50%", "50%" },
})

hl.window_rule({
    name  = "center_8",
    match = {
        class = "^(copyq)$",
    },
    center = true,
})

hl.window_rule({
    name  = "stayfocused_9",
    match = {
        title = "^/.*",
        class = "^(steam)$",
    },
    stay_focused = true,
})

hl.window_rule({
    name  = "tile_10",
    match = {
        class = "^(firefox)$",
    },
    tile = true,
})

hl.window_rule({
    name  = "rounding_12_12",
    match = {
        float = true,
    },
    rounding = 12,
})

-- --- Regras de Camada (Layers) ---

hl.layer_rule({
    match = {
        namespace = "swaync",
    },
    no_anim = true,
})

hl.layer_rule({
    match = {
        namespace = "swaync",
    },
    blur = true,
})

hl.layer_rule({
    match = {
        namespace = "swaync",
    },
    ignore_alpha = 0.5,
})

hl.layer_rule({
    match = {
        namespace = "rofi",
    },
    animation = "popin 80%",
})

hl.layer_rule({
    match = {
        namespace = "rofi",
    },
    blur = true,
})

hl.layer_rule({
    match = {
        namespace = "rofi",
    },
    ignore_alpha = 0.5,
})

hl.layer_rule({
    match = {
        namespace = "waybar",
    },
    blur = true,
})

hl.layer_rule({
    match = {
        namespace = "waybar",
    },
    ignore_alpha = 0.2,
})
