-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- --- Inicialização ---
















-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("~/.config/hypr/scripts/wallpaper.sh &")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface gtk-theme 'Catppuccin-Mocha-Standard-Blue-Dark'")
    hl.exec_cmd("~/.config/waybar/start.sh")
    hl.exec_cmd("~/.config/hypr/scripts/border-animate.sh")
    hl.exec_cmd("nm-applet")
    hl.exec_cmd("blueman-applet")
    hl.exec_cmd("/usr/libexec/polkit-kde-authentication-agent-1")
    hl.exec_cmd("swaync")
    hl.exec_cmd("copyq")
    hl.exec_cmd("~/.config/hypr/scripts/battery_notification.sh")
    hl.exec_cmd("~/.config/hypr/scripts/clipboard_daemon.sh")
    hl.exec_cmd("~/.config/hypr/scripts/check_updates")
    hl.exec_cmd("hypridle")
end)
