-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- ==========================================

-- HYPRLAND CONFIGURATION INDEX

-- ==========================================

-- Tema de Cores (Catppuccin)

-- source = ~/.config/hypr/mocha.conf -> requires manual conversion
local mocha = require("mocha")
-- TODO: convert ~/.config/hypr/mocha.conf to .lua and use require()

-- Módulos de Configuração

-- source = ~/.config/hypr/conf/env.conf -> requires manual conversion
local env = require("conf.env")
-- TODO: convert ~/.config/hypr/conf/env.conf to .lua and use require()

-- source = ~/.config/hypr/conf/startup.conf -> requires manual conversion
local startup = require("conf.startup")
-- TODO: convert ~/.config/hypr/conf/startup.conf to .lua and use require()

-- source = ~/.config/hypr/conf/input.conf -> requires manual conversion
local input = require("conf.input")
-- TODO: convert ~/.config/hypr/conf/input.conf to .lua and use require()

-- source = ~/.config/hypr/conf/appearance.conf -> requires manual conversion
local appearance = require("conf.appearance")
-- TODO: convert ~/.config/hypr/conf/appearance.conf to .lua and use require()

-- source = ~/.config/hypr/conf/rules.conf -> requires manual conversion
local rules = require("conf.rules")
-- TODO: convert ~/.config/hypr/conf/rules.conf to .lua and use require()

-- source = ~/.config/hypr/conf/keybinds.conf -> requires manual conversion
local keybinds = require("conf.keybinds")
-- TODO: convert ~/.config/hypr/conf/keybinds.conf to .lua and use require()
