general {
    lock_cmd = ~/.config/hypr/scripts/lock.sh
}

# Apagar o monitor após 10 minutos de inatividade, sem senha
listener {
    timeout = 6000
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
