# ==========================================
# HYPRLAND CONFIGURATION INDEX
# ==========================================

# Tema de Cores (Catppuccin)
source = ~/.config/hypr/mocha.conf

# Módulos de Configuração
source = ~/.config/hypr/conf/env.conf
source = ~/.config/hypr/conf/startup.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/appearance.conf
source = ~/.config/hypr/conf/rules.conf
source = ~/.config/hypr/conf/keybinds.conf
